set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
set softtabstop=4
set autoindent
set nu
 
filetype plugin on

syntax on
set background=dark
 
" This will show any extraneous whitespace at the end of lines, and make visible any tab characters
set list
set listchars=tab:>-,trail:^ 
